language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hFSjWqgKqJvccTFxb6eL+OKVr1lr0CCRO4JaDSeuc2r6G48yJ1gke0Z0sp5ThdwzvL3ZG4ZbVcYX7qautXNfhXQi2Fuw7Nu/bswHnSqDNF8rtJKQz9fuudaqK6cPvOpZptg4ZlgjLEDtajSULCoIX+kG/7MJtumoHC/AAnpbKhRx+CgPk3Ikq1CpQJgLoYFOMv86y2MaRDTAzKNfhMB6cwWwpKnkoAxNISoqT7bvxFo+pBLN9YifAaKAXXgMs+LnKopRpXclWKfJjxyn+XB8GZ+wOkxImaZU6v8lrncdkWZqGH6Q1q+REghpSIgcv4dQ39uhu6Pqp7yZTAXT5hCovw6KYcIRp9SqzVzUjloiWU4vohO/dAafk4I2R1afJWP4ZTpXHNQWlb52eH3AfhEiHeLfWGBX+3Xtu2MUnjT3yKQgc9yduT+zN8rC5Zpou+A6btAmbdT8EACrjMt8rmaUnsQpcYCwFGVYeSv3qYVEJXa3VJgw90v4oMTncfUH7xqT7v4lQ5g/QiVBqqls6Th2vfusAoX8yDTsLAOUB/Xz5jkakLw2gm2ZXcyIt/1yGXJCX10Nvgp84P40lqbFlEt5ZFOZ1ErMzcNnyLkg7MF2OK6PVKV0WFT/J1mZEXL6VpzewnhCC2SzpYwVgfuW0l6MB+hsSkt/2paYw0DfHEfM1ro=
  app: sleepy-ocean-63091
  on:
    repo: ike76/blog-app-mongoose
